### PR TITLE
feat: use map for owners, encrypters and decrypters

### LINKED ISSUE #73: Can't set more than one encrypter/decrypter for a key
### TL;DR

Setting more than one entity in `encrypters` and `decrypters` does not work. The other entities other than the first get silently ignored.

### Expected behavior

All entities in `encrypters` and `decrypters` are given the roles `roles/cloudkms.cryptoKeyEncrypter` and `roles/cloudkms.cryptoKeyDecrypter`

### Observed behavior

Adding a second entity to `encrypters` and `decrypters` does nothing.

### Terraform Configuration
This adds the roles `roles/cloudkms.cryptoKeyEncrypter` and `roles/cloudkms.cryptoKeyDecrypter` to the service account `google_service_account.kanister`.

```hcl
module "kms" {
  source  = "registry.terraform.io/terraform-google-modules/kms/google"
  version = "2.2.1"

  project_id = var.project.name
  location   = "europe"
  keyring    = "backup"
  keys       = ["kanister"]

  encrypters = [
    "serviceAccount:${google_service_account.kanister.email}",
  ]
  decrypters = [
    "serviceAccount:${google_service_account.kanister.email}",
  ]

  set_encrypters_for = ["kanister"]
  set_decrypters_for = ["kanister"]
}
```

Adding a secondary account does nothing:
```hcl
module "kms" {
  source  = "registry.terraform.io/terraform-google-modules/kms/google"
  version = "2.2.1"

  project_id = var.project.name
  location   = "europe"
  keyring    = "backup"
  keys       = ["kanister"]

  encrypters = [
    "serviceAccount:${google_service_account.kanister.email}",
    "serviceAccount:service-2342@gs-project-accounts.iam.gserviceaccount.com",
  ]
  decrypters = [
    "serviceAccount:${google_service_account.kanister.email}",
    "serviceAccount:service-2342@gs-project-accounts.iam.gserviceaccount.com",
  ]

  set_encrypters_for = ["kanister"]
  set_decrypters_for = ["kanister"]
}
```

### Terraform Version

```sh
Terraform v1.3.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v4.44.1
+ provider registry.terraform.io/hashicorp/google-beta v4.44.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.16.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by muffl0n**
Fixes #73.

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@muffl0n
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_documentation
 The documentation needs to be regenerated. Please run `make generate_docs`. 
 ```bash 
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/README.md /tmp/tmp.RCAlw18VDS/generate_docs/workspace/README.md
52,53c52,53
< | decrypters | List of comma-separated owners for each key declared in set\_decrypters\_for. | `list(string)` | `[]` | no |
< | encrypters | List of comma-separated owners for each key declared in set\_encrypters\_for. | `list(string)` | `[]` | no |
---
> | decrypters | Map of decrypter for each key. | `map(list(string))` | `{}` | no |
> | encrypters | Map of encrypter for each key. | `map(list(string))` | `{}` | no |
61c61
< | owners | List of comma-separated owners for each key declared in set\_owners\_for. | `list(string)` | `[]` | no |
---
> | owners | Map of owners for each key. | `map(list(string))` | `{}` | no |
65,67d64
< | set\_decrypters\_for | Name of keys for which decrypters will be set. | `list(string)` | `[]` | no |
< | set\_encrypters\_for | Name of keys for which encrypters will be set. | `list(string)` | `[]` | no |
< | set\_owners\_for | Name of keys for which owners will be set. | `list(string)` | `[]` | no |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
 ``` 
- ⚠️check_whitespace
 Failed whitespace check. More details below. 
 ```bash 
Checking for trailing whitespace
./README.md:31:  
./README.md:32:  owners = { 
Error: Trailing whitespace found in the lines above.
Checking for missing newline at end of file
 ``` 
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
Running terraform validate
terraform_validate .
╷
│
 
Error: 
Reference to undeclared local value
│
 
│
 
  on outputs.tf line 43, in output "keys":
│
 
  43:   value       = 
local.keys_by_name
│
 
│
 
A local value with the name "keys_by_name" has not been declared.
╵
terraform_validate ./examples/simple_example
╷
│
 
Error: 
Reference to undeclared local value
│
 
│
 
  on ../../outputs.tf line 43, in output "keys":
│
 
  43:   value       = 
local.keys_by_name
│
 
│
 
A local value with the name "keys_by_name" has not been declared.
╵
terraform_validate ./test/fixtures/simple_example
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on main.tf line 18, in provider "random":
│
 
  18:   version = 
"~> 2.0"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
╵
╷
│
 
Error: 
Reference to undeclared local value
│
 
│
 
  on ../../../outputs.tf line 43, in output "keys":
│
 
  43:   value       = 
local.keys_by_name
│
 
│
 
A local value with the name "keys_by_name" has not been declared.
╵
terraform_validate ./test/setup
Success!
 The configuration is valid.
 ```

**Comment by comment-bot-dev** [comment]
@muffl0n
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_documentation
 The documentation needs to be regenerated. Please run `make generate_docs`. 
 ```bash 
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/README.md /tmp/tmp.zoiVsqZNf5/generate_docs/workspace/README.md
52,53c52,53
< | decrypters | List of comma-separated owners for each key declared in set\_decrypters\_for. | `list(string)` | `[]` | no |
< | encrypters | List of comma-separated owners for each key declared in set\_encrypters\_for. | `list(string)` | `[]` | no |
---
> | decrypters | Map of decrypter for each key. | `map(list(string))` | `{}` | no |
> | encrypters | Map of encrypter for each key. | `map(list(string))` | `{}` | no |
61c61
< | owners | List of comma-separated owners for each key declared in set\_owners\_for. | `list(string)` | `[]` | no |
---
> | owners | Map of owners for each key. | `map(list(string))` | `{}` | no |
65,67d64
< | set\_decrypters\_for | Name of keys for which decrypters will be set. | `list(string)` | `[]` | no |
< | set\_encrypters\_for | Name of keys for which encrypters will be set. | `list(string)` | `[]` | no |
< | set\_owners\_for | Name of keys for which owners will be set. | `list(string)` | `[]` | no |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
 ``` 
- ⚠️check_whitespace
 Failed whitespace check. More details below. 
 ```bash 
Checking for trailing whitespace
./README.md:31:  
./README.md:32:  owners = { 
Error: Trailing whitespace found in the lines above.
Checking for missing newline at end of file
 ``` 
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
Running terraform validate
terraform_validate .
╷
│
 
Error: 
Reference to undeclared local value
│
 
│
 
  on outputs.tf line 43, in output "keys":
│
 
  43:   value       = 
local.keys_by_name
│
 
│
 
A local value with the name "keys_by_name" has not been declared.
╵
terraform_validate ./examples/simple_example
╷
│
 
Error: 
Reference to undeclared local value
│
 
│
 
  on ../../outputs.tf line 43, in output "keys":
│
 
  43:   value       = 
local.keys_by_name
│
 
│
 
A local value with the name "keys_by_name" has not been declared.
╵
terraform_validate ./test/fixtures/simple_example
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on main.tf line 18, in provider "random":
│
 
  18:   version = 
"~> 2.0"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
╵
╷
│
 
Error: 
Reference to undeclared local value
│
 
│
 
  on ../../../outputs.tf line 43, in output "keys":
│
 
  43:   value       = 
local.keys_by_name
│
 
│
 
A local value with the name "keys_by_name" has not been declared.
╵
terraform_validate ./test/setup
Success!
 The configuration is valid.
 ```

**Comment by comment-bot-dev** [comment]
@muffl0n
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_whitespace
 Failed whitespace check. More details below. 
 ```bash 
Checking for trailing whitespace
./README.md:31:  
./README.md:32:  owners = { 
Error: Trailing whitespace found in the lines above.
Checking for missing newline at end of file
 ``` 
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
Running terraform validate
terraform_validate .
╷
│
 
Error: 
Reference to undeclared local value
│
 
│
 
  on outputs.tf line 43, in output "keys":
│
 
  43:   value       = 
local.keys_by_name
│
 
│
 
A local value with the name "keys_by_name" has not been declared.
╵
terraform_validate ./examples/simple_example
╷
│
 
Error: 
Reference to undeclared local value
│
 
│
 
  on ../../outputs.tf line 43, in output "keys":
│
 
  43:   value       = 
local.keys_by_name
│
 
│
 
A local value with the name "keys_by_name" has not been declared.
╵
terraform_validate ./test/fixtures/simple_example
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on main.tf line 18, in provider "random":
│
 
  18:   version = 
"~> 2.0"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
╵
╷
│
 
Error: 
Reference to undeclared local value
│
 
│
 
  on ../../../outputs.tf line 43, in output "keys":
│
 
  43:   value       = 
local.keys_by_name
│
 
│
 
A local value with the name "keys_by_name" has not been declared.
╵
terraform_validate ./test/setup
Success!
 The configuration is valid.
 ```

**Comment by comment-bot-dev** [comment]
@muffl0n
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_whitespace
 Failed whitespace check. More details below. 
 ```bash 
Checking for trailing whitespace
./README.md:31:  
Error: Trailing whitespace found in the lines above.
Checking for missing newline at end of file
 ```

**Comment by comment-bot-dev** [comment]
@muffl0n
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by muffl0n** [comment]
Is there any chance that this will get merged?

**Comment by apeabody** [comment]
Thanks for the contribution @muffl0n!  Here is some relevant output from the INT test:

```
│ Error: Invalid function argument
│ 
│   on ../../../examples/simple_example/outputs.tf line 29, in output "keys":
│   29:   value       = keys(module.kms.keys)
│     ├────────────────
│     │ module.kms.keys is list of string with 2 elements
│ 
│ Invalid value for "inputMap" parameter: must have map or object type.
╵}
```

When ready, please mark as "Ready for review".  Thanks!

**Comment by pnancarrow** [comment]
would love to see this merged

**Comment by muffl0n** [comment]
I moved on and can't work on this PR anymore.

**Pull request closed without merging**
