### PR TITLE
feat: Add support for purpose variable

### PR DESCRIPTION
**Pull request by akovtun-extenda**
https://cloud.google.com/kms/docs/reference/rest/v1/projects.locations.keyRings.cryptoKeys#CryptoKeyPurpose

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_documentation
 The documentation needs to be regenerated. Please run `make generate_docs`. 
 ```bash 
Checking for documentation generation
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/README.md /tmp/tmp.zNgnDtyGn9/generate_docs/workspace/README.md
45,61c45,61
< |------|-------------|:----:|:-----:|:-----:|
< | decrypters | List of comma-separated owners for each key declared in set_decrypters_for. | list(string) | `<list>` | no |
< | encrypters | List of comma-separated owners for each key declared in set_encrypters_for. | list(string) | `<list>` | no |
< | key\_algorithm | The algorithm to use when creating a version based on this template. See the https://cloud.google.com/kms/docs/reference/rest/v1/CryptoKeyVersionAlgorithm for possible inputs. | string | `"GOOGLE_SYMMETRIC_ENCRYPTION"` | no |
< | key\_protection\_level | The protection level to use when creating a version based on this template. Default value: "SOFTWARE" Possible values: ["SOFTWARE", "HSM"] | string | `"SOFTWARE"` | no |
< | key\_rotation\_period |  | string | `"100000s"` | no |
< | keyring | Keyring name. | string | n/a | yes |
< | keys | Key names. | list(string) | `<list>` | no |
< | labels | Labels, provided as a map | map(string) | `<map>` | no |
< | location | Location for the keyring. | string | n/a | yes |
< | owners | List of comma-separated owners for each key declared in set_owners_for. | list(string) | `<list>` | no |
< | prevent\_destroy | Set the prevent_destroy lifecycle attribute on keys. | string | `"true"` | no |
< | project\_id | Project id where the keyring will be created. | string | n/a | yes |
< | purpose | The immutable purpose of the CryptoKey. Possible values are ENCRYPT_DECRYPT, ASYMMETRIC_SIGN, and ASYMMETRIC_DECRYPT | string | `ENCRYPT_DECRYPT` | no |
< | set\_decrypters\_for | Name of keys for which decrypters will be set. | list(string) | `<list>` | no |
< | set\_encrypters\_for | Name of keys for which encrypters will be set. | list(string) | `<list>` | no |
< | set\_owners\_for | Name of keys for which owners will be set. | list(string) | `<list>` | no |
---
> |------|-------------|------|---------|:--------:|
> | decrypters | List of comma-separated owners for each key declared in set\_decrypters\_for. | `list(string)` | `[]` | no |
> | encrypters | List of comma-separated owners for each key declared in set\_encrypters\_for. | `list(string)` | `[]` | no |
> | key\_algorithm | The algorithm to use when creating a version based on this template. See the https://cloud.google.com/kms/docs/reference/rest/v1/CryptoKeyVersionAlgorithm for possible inputs. | `string` | `"GOOGLE_SYMMETRIC_ENCRYPTION"` | no |
> | key\_protection\_level | The protection level to use when creating a version based on this template. Default value: "SOFTWARE" Possible values: ["SOFTWARE", "HSM"] | `string` | `"SOFTWARE"` | no |
> | key\_rotation\_period | n/a | `string` | `"100000s"` | no |
> | keyring | Keyring name. | `string` | n/a | yes |
> | keys | Key names. | `list(string)` | `[]` | no |
> | labels | Labels, provided as a map | `map(string)` | `{}` | no |
> | location | Location for the keyring. | `string` | n/a | yes |
> | owners | List of comma-separated owners for each key declared in set\_owners\_for. | `list(string)` | `[]` | no |
> | prevent\_destroy | Set the prevent\_destroy lifecycle attribute on keys. | `bool` | `true` | no |
> | project\_id | Project id where the keyring will be created. | `string` | n/a | yes |
> | purpose | The immutable purpose of the CryptoKey. Possible values are ENCRYPT\_DECRYPT, ASYMMETRIC\_SIGN, and ASYMMETRIC\_DECRYPT. | `string` | `"ENCRYPT_DECRYPT"` | no |
> | set\_decrypters\_for | Name of keys for which decrypters will be set. | `list(string)` | `[]` | no |
> | set\_encrypters\_for | Name of keys for which encrypters will be set. | `list(string)` | `[]` | no |
> | set\_owners\_for | Name of keys for which owners will be set. | `list(string)` | `[]` | no |
diff -r '--exclude=.terraform' '--exclude=.kitchen' '--exclude=.git' '--exclude=autogen' '--exclude=*.tfvars' /workspace/examples/simple_example/README.md /tmp/tmp.zNgnDtyGn9/generate_docs/workspace/examples/simple_example/README.md
9,13c9,13
< |------|-------------|:----:|:-----:|:-----:|
< | keyring | Keyring name. | string | n/a | yes |
< | keys | Key names. | list(string) | `<list>` | no |
< | location | Location for the keyring. | string | `"global"` | no |
< | project\_id | The ID of the project in which to provision resources. | string | n/a | yes |
---
> |------|-------------|------|---------|:--------:|
> | keyring | Keyring name. | `string` | n/a | yes |
> | keys | Key names. | `list(string)` | `[]` | no |
> | location | Location for the keyring. | `string` | `"global"` | no |
> | project\_id | The ID of the project in which to provision resources. | `string` | n/a | yes |
Error: Documentation generation has not been run, please run the
'make docker_generate_docs' command and commit the above changes.
 ``` 
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
Running terraform validate
terraform_validate . 
Success!
 The configuration is valid.
terraform_validate ./examples/simple_example 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/simple_example 
Warning: 
Interpolation-only expressions are deprecated
  on outputs.tf line 34, in output "project_id":
  34:   value       = 
"${var.project_id}"
Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.
Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.
Success!
 The configuration is valid, but there were some validation warnings as shown above.
terraform_validate ./test/setup 
Error: 
Unsupported Terraform Core version
  on .terraform/modules/project_ci_kms/versions.tf line 18, in terraform:
  18:   
required_version = "~> 0.12.6"
Module module.project_ci_kms (from
terraform-google-modules/project-factory/google) does not support Terraform
version 0.13.5. To proceed, either choose another supported Terraform version
or update this version constraint. Version constraints are normally set for
good reason, so updating the constraint may lead to other errors or unexpected
behavior.
Error: 
Unsupported Terraform Core version
  on .terraform/modules/project_ci_kms/modules/budget/versions.tf line 18, in terraform:
  18:   
required_version = "~> 0.12.6"
Module module.project_ci_kms.module.budget (from ./modules/budget) does not
support Terraform version 0.13.5. To proceed, either choose another supported
Terraform version or update this version constraint. Version constraints are
normally set for good reason, so updating the constraint may lead to other
errors or unexpected behavior.
Error: 
Unsupported Terraform Core version
  on .terraform/modules/project_ci_kms/modules/core_project_factory/versions.tf line 18, in terraform:
  18:   
required_version = "~> 0.12.6"
Module module.project_ci_kms.module.project-factory (from
./modules/core_project_factory) does not support Terraform version 0.13.5. To
proceed, either choose another supported Terraform version or update this
version constraint. Version constraints are normally set for good reason, so
updating the constraint may lead to other errors or unexpected behavior.
Error: 
Unsupported Terraform Core version
  on .terraform/modules/project_ci_kms/modules/gsuite_group/versions.tf line 18, in terraform:
  18:   
required_version = "~> 0.12.6"
Module module.project_ci_kms.module.gsuite_group (from ./modules/gsuite_group)
does not support Terraform version 0.13.5. To proceed, either choose another
supported Terraform version or update this version constraint. Version
constraints are normally set for good reason, so updating the constraint may
lead to other errors or unexpected behavior.
Error: 
Unsupported Terraform Core version
  on .terraform/modules/project_ci_kms/modules/project_services/versions.tf line 18, in terraform:
  18:   
required_version = "~> 0.12.6"
Module module.project_ci_kms.module.project-factory.module.project_services
(from ../project_services) does not support Terraform version 0.13.5. To
proceed, either choose another supported Terraform version or update this
version constraint. Version constraints are normally set for good reason, so
updating the constraint may lead to other errors or unexpected behavior.
 ```

**Review by morgante — APPROVED** [review]

**Review by morgante — APPROVED** [review]

**Comment by morgante** [comment]
@akovtun-extenda Please rebase on `master`.

**Comment by akovtun-extenda** [comment]
@morgante Can you please take a look again?

**Comment by morgante** [comment]
@akovtun-extenda Please regenerate docs.

**Comment by artemlive** [comment]
Hey guys, are there any updates?

**Comment by artemlive** [comment]
There is a new issue that will appear after merging this. 
`key_rotation_period ` has to be explicitly set to null if you want to use the ASYMMETRIC_SIGN purpose, maybe it has to be fixed in the module definition. 
Something like that:
`  rotation_period = var.purpose == "GOOGLE_SYMMETRIC_ENCRYPTION" ? var.key_rotation_period : null
`

**Comment by akovtun-extenda** [comment]
there is a default value for `key_rotation_period`:
```
variable "key_rotation_period" {
  type    = string
  default = "100000s"
}
```
and with `purpose  = "ASYMMETRIC_SIGN"` we have set  rotation period as this `key_rotation_period = ""`

**Comment by morgante** [comment]
Linters and tests are still failing.

**Comment by akovtun-extenda** [comment]
error from tests:
```
Profile Summary: 1 successful control, 0 control failures, 0 controls skipped
Test Summary: 6 successful, 0 failures, 0 skipped
$$$$$$ Finished verifying the 'simple_example local' system.
$$$$$$ Verifying the 'simple_example gcp' system...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [cannot load such file -- google/apis/dns_v2beta1] on simple-example-default
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Review by morgante — APPROVED** [review]
Test failure is unrelated.

**Comment by bharathkkb** [comment]
fixed via https://github.com/terraform-google-modules/terraform-google-kms/pull/59

**Pull request closed without merging**
