### PR TITLE
fix: Remove non-needed counts on Autokey submodule

### PR DESCRIPTION
**Pull request by romanini-ciandt**
The goal of this PR is to remove a non-needed "count". Removing this can avoid some terraform dependencies issues.

### CODE REVIEW

**Review by tdbhacks — APPROVED** [review]
Seems reasonable to me!

**Comment by romanini-ciandt** [comment]
@apeabody is it possible to merge this PR?
If yes, could we cut a new release after that, please?

**Review by apeabody — APPROVED** [review]
Approved by @tdbhacks

**Comment by romanini-ciandt** [comment]
> > @apeabody is it possible to merge this PR? If yes, could we cut a new release after that, please?
> 
> Hi @romanini-ciandt - Should this PR be a "fix" to be included in the release notes?

Makes sense! It's updated!

**Comment by apeabody** [comment]
> > > @apeabody is it possible to merge this PR? If yes, could we cut a new release after that, please?
> > 
> > 
> > Hi @romanini-ciandt - Should this PR be a "fix" to be included in the release notes?
> 
> @apeabody makes sense! It's updated!

Thanks @romanini-ciandt!  Happy to do the release, can you please have https://github.com/terraform-google-modules/terraform-google-kms/pull/157 approved to indicate it's ready. Thanks!

**Comment by romanini-ciandt** [comment]
Thanks so much for all your support @apeabody :)

**Pull request merged**
